name: btc-full
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pandas>=2.0
  - numpy>=1.26
  - pyarrow>=15
  - requests>=2.31
  - python-dotenv>=1.0
  - apscheduler>=3.10
  - scikit-learn>=1.4
  - lightgbm>=4.3
  - scipy>=1.11
  - joblib>=1.3
  - pytorch>=2.1       # CPU build for macOS; uses Apple MPS where available
  - pip
  - pip:
      - ccxt>=4.3.98
      - pytrends>=4.9.2
